language: python
python:
  - "3.5"
  - "3.6"      # current detault Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - python setup.py develop
# command to run tests
script:
  - make test